project:
  type: book
  output-dir: docs

book:
  title: "Book1"
  author: "Norah Jones"
  date: "12/4/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf, epub]
bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt

editor: visual

